import './globals.css';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import Navbar from '@/shared/templates/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Tomato Barbershop',
    description: 'Generated by create next app, author: Tomatomir',
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
